AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: get_brand_count for B e s t - S h o e s . c o m
Resources:
  getbrandcount:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: .
      Description: get_brand_count for B e s t - S h o e s . c o m
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::[account_number]:role/lambda_dynamoDB_lambda_function'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /MyResource
            Method: ANY
